
// 
// This code was generated by a script. Any changes made manually will be lost
// the next time this code is regenerated.
//

using System.Reflection;
using System.Resources;

// General Information
[assembly: AssemblyTitle("MDLZ mRemoteNG")]
[assembly: AssemblyDescription("Multi-Remote Next Generation Connection Manager")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("HCLTech")]
[assembly: AssemblyProduct("MDLZ mRemoteNG Connection Manager")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Version information
[assembly: AssemblyVersion("2.0.6.11")]
[assembly: AssemblyFileVersion("2.0.6.11")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersion("2.0.6 ( 11)")]

// Logging
[assembly: log4net.Config.XmlConfigurator(ConfigFile = "log4net.config")]

